# Generated by Django 4.2.13 on 2026-08-12 12:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register Citizen'), ('PIN_CHANGE', 'PIN Changed'), ('OFFICER_CREATE', 'Officer Created'), ('OFFICER_UPDATE', 'Officer Updated'), ('OFFICER_DEACTIVATE', 'Officer Deactivated'), ('CAMPAIGN_CREATE', 'Campaign Created'), ('CAMPAIGN_UPDATE', 'Campaign Updated'), ('PIN_RESET', 'PIN Reset')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(choices=[('CITIZEN', 'Citizen'), ('OFFICER', 'Officer'), ('CAMPAIGN', 'Campaign'), ('REGISTRATION', 'Registration')], max_length=50)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, help_text='ID Number from Excel (stored as VARCHAR to preserve leading zeros)', max_length=20, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('tribe', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^(\\+254|0)?[1-9]\\d{8}$', 'Invalid Kenyan phone format')])),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('division', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('sub_location', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('registration_status', models.CharField(choices=[('UNREGISTERED', 'Unregistered'), ('REGISTERED', 'Registered')], db_index=True, default='UNREGISTERED', max_length=20)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, help_text='Source Excel filename', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citizen',
                'verbose_name_plural': 'Citizens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('county', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('sheet_name', models.CharField(default='Gaps', max_length=100)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of error records')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, help_text='Officer national ID (8 digits)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'Must be 8 digits')])),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\+254|0)[1-9]\\d{8}$', 'Must be valid Kenyan format')])),
                ('role', models.CharField(choices=[('REGISTRATION_OFFICER', 'Registration Officer'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRATOR', 'Administrator')], default='REGISTRATION_OFFICER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20)),
                ('pin_hash', models.CharField(help_text='bcrypt hashed PIN', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device metadata')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaign')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.citizen')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.officer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='core.officer')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerAssignedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_locations', to='core.officer')),
            ],
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['national_id'], name='core_office_nationa_5ef1da_idx'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['status'], name='core_office_status_eaf792_idx'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['role'], name='core_office_role_7a92c2_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['status'], name='core_import_status_dddead_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['county'], name='core_import_county_7f8200_idx'),
        ),
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['created_at'], name='core_import_created_a10b3d_idx'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_citizens', to='core.campaign'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_citizens', to='core.officer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to='core.officer'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.officer'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['citizen'], name='core_regist_citizen_6a48f6_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['officer'], name='core_regist_officer_77ccda_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['campaign'], name='core_regist_campaig_fc91d6_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['created_at'], name='core_regist_created_916ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['officer', 'revoked'], name='core_refres_officer_8199cc_idx'),
        ),
        migrations.AddIndex(
            model_name='refreshtoken',
            index=models.Index(fields=['expires_at'], name='core_refres_expires_39178f_idx'),
        ),
        migrations.AddIndex(
            model_name='officerassignedlocation',
            index=models.Index(fields=['officer', 'district'], name='core_office_officer_5ea6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='officerassignedlocation',
            index=models.Index(fields=['county'], name='core_office_county_debe08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='officerassignedlocation',
            unique_together={('officer', 'county', 'district', 'division', 'location')},
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['national_id'], name='core_citize_nationa_be9871_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['registration_status'], name='core_citize_registr_b37460_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['county', 'district'], name='core_citize_county_e499d5_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['division', 'location'], name='core_citize_divisio_1db8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['created_at'], name='core_citize_created_1f281f_idx'),
        ),
        migrations.AddIndex(
            model_name='citizen',
            index=models.Index(fields=['full_name'], name='core_citize_full_na_c3402d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status'], name='core_campai_status_36ec94_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='core_campai_start_d_c3f578_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='core_auditl_user_id_4f5b78_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'),
        ),
    ]
