# Generated by Django 4.2.13 on 2026-08-12 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^(\\+254|0)?[1-9]\\d{8}$', 'Invalid Kenyan phone format')]),
        ),
    ]
