# Generated by Django 4.2.13 on 2026-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_citizen_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register Citizen'), ('PIN_CHANGE', 'PIN Changed'), ('PIN_ISSUED', 'PIN Issued'), ('OFFICER_CREATE', 'Officer Created'), ('OFFICER_UPDATE', 'Officer Updated'), ('OFFICER_DEACTIVATE', 'Officer Deactivated'), ('CAMPAIGN_CREATE', 'Campaign Created'), ('CAMPAIGN_UPDATE', 'Campaign Updated'), ('PIN_RESET', 'PIN Reset'), ('VERIFICATION_APPROVE', 'Verification Approved'), ('VERIFICATION_REJECT', 'Verification Rejected')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='officer',
            name='national_id',
            field=models.CharField(db_index=True, help_text='Officer national ID (8 digits) or admin email for admin accounts', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
