"""
Core models for SDICS.
"""

from django.db import models
from django.core.validators import RegexValidator
from django.utils import timezone
import uuid


# ==================== Officer Models ====================

class Officer(models.Model):
    """
    Authorized registration professional identified by national_id.
    PIN is generated by system, hashed with bcrypt, never stored plaintext.
    """
    ROLE_CHOICES = [
        ('REGISTRATION_OFFICER', 'Registration Officer'),
        ('SUPERVISOR', 'Supervisor'),
        ('ADMINISTRATOR', 'Administrator'),
    ]

    STATUS_CHOICES = [
        ('ACTIVE', 'Active'),
        ('INACTIVE', 'Inactive'),
        ('SUSPENDED', 'Suspended'),
    ]

    national_id = models.CharField(
        max_length=100,
        unique=True,
        db_index=True,
        help_text='Officer national ID (8 digits) or admin email for admin accounts'
    )
    full_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=20, blank=True, default='')
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='REGISTRATION_OFFICER')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='ACTIVE', db_index=True)
    pin_hash = models.CharField(max_length=255, help_text='bcrypt hashed PIN')
    last_login = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['national_id']),
            models.Index(fields=['status']),
            models.Index(fields=['role']),
        ]

    def __str__(self):
        return f"{self.full_name} ({self.national_id})"


class OfficerAssignedLocation(models.Model):
    """
    Geographical locations assigned to each officer.
    Officers can only register citizens in their assigned locations.
    """
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE, related_name='assigned_locations')
    county = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    district = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    division = models.CharField(max_length=100, null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('officer', 'county', 'district', 'division', 'location')
        indexes = [
            models.Index(fields=['officer', 'district']),
            models.Index(fields=['county']),
        ]

    def __str__(self):
        return f"{self.officer.full_name} - {self.county}/{self.district}"


class RefreshToken(models.Model):
    """
    Stores refresh tokens for revocation capability.
    Allows invalidating tokens when officer logs out or is deactivated.
    """
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE, related_name='refresh_tokens')
    token_hash = models.CharField(max_length=255, unique=True, db_index=True)
    expires_at = models.DateTimeField(db_index=True)
    revoked = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['officer', 'revoked']),
            models.Index(fields=['expires_at']),
        ]

    def __str__(self):
        return f"{self.officer.national_id} - {'Revoked' if self.revoked else 'Valid'}"


# ==================== Campaign Models ====================

class Campaign(models.Model):
    """
    Registration campaign with start/end dates, targets, and status.
    """
    STATUS_CHOICES = [
        ('PLANNED', 'Planned'),
        ('ACTIVE', 'Active'),
        ('CLOSED', 'Closed'),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    target_count = models.IntegerField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PLANNED', db_index=True)
    created_by = models.ForeignKey(Officer, on_delete=models.SET_NULL, null=True, related_name='created_campaigns')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['status']),
            models.Index(fields=['start_date', 'end_date']),
        ]

    def __str__(self):
        return f"{self.name} ({self.status})"


# ==================== Citizen Models ====================

class Citizen(models.Model):
    """
    Unregistered citizen from Excel dataset.
    Schema matches actual Excel columns: Full Name, Sex, District, Division, Location, Sub Location, Village, ID Number, Date of Birth, Tribe, Phone Numbers.
    """
    SEX_CHOICES = [
        ('MALE', 'Male'),
        ('FEMALE', 'Female'),
        ('OTHER', 'Other'),
        ('UNKNOWN', 'Unknown'),
    ]

    STATUS_CHOICES = [
        ('UNREGISTERED', 'Unregistered'),
        ('REGISTERED', 'Registered'),
    ]

    # Primary identifier: national_id from Excel "ID Number" column
    national_id = models.CharField(
        max_length=20,
        unique=True,
        db_index=True,
        help_text='ID Number from Excel (stored as VARCHAR to preserve leading zeros)'
    )

    # Basic information from Excel
    full_name = models.CharField(max_length=255, db_index=True)
    sex = models.CharField(max_length=20, choices=SEX_CHOICES, default='UNKNOWN')
    date_of_birth = models.DateField(null=True, blank=True)
    tribe = models.CharField(max_length=100, null=True, blank=True)
    phone_number = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        validators=[RegexValidator(r'^(\+254|0)?[1-9]\d{8}$', 'Invalid Kenyan phone format')]
    )

    # Hierarchical location from Excel
    county = models.CharField(max_length=100, db_index=True)
    district = models.CharField(max_length=100, db_index=True)
    division = models.CharField(max_length=100, db_index=True)
    location = models.CharField(max_length=100, db_index=True)
    sub_location = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    village = models.CharField(max_length=100, null=True, blank=True, db_index=True)

    # Registration tracking
    registration_status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='UNREGISTERED',
        db_index=True
    )
    registered_at = models.DateTimeField(null=True, blank=True)
    registered_by = models.ForeignKey(
        Officer,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='registered_citizens'
    )
    campaign = models.ForeignKey(
        Campaign,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='registered_citizens'
    )

    # Import tracking
    source_file = models.CharField(max_length=255, null=True, blank=True, help_text='Source Excel filename')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['national_id']),
            models.Index(fields=['registration_status']),
            models.Index(fields=['county', 'district']),
            models.Index(fields=['division', 'location']),
            models.Index(fields=['created_at']),
            models.Index(fields=['full_name']),  # For search
        ]
        verbose_name = 'Citizen'
        verbose_name_plural = 'Citizens'

    def __str__(self):
        return f"{self.full_name} ({self.national_id})"


# ==================== Registration Models ====================

class Registration(models.Model):
    """
    Records each citizen registration event with metadata.
    """
    citizen = models.ForeignKey(Citizen, on_delete=models.CASCADE, related_name='registrations')
    officer = models.ForeignKey(Officer, on_delete=models.SET_NULL, null=True, related_name='registrations')
    campaign = models.ForeignKey(Campaign, on_delete=models.SET_NULL, null=True, blank=True)
    registered_at = models.DateTimeField()
    location = models.CharField(max_length=100, null=True, blank=True)
    device_info = models.JSONField(default=dict, blank=True, help_text='Device metadata')
    ip_address = models.CharField(max_length=45, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['citizen']),
            models.Index(fields=['officer']),
            models.Index(fields=['campaign']),
            models.Index(fields=['created_at']),
        ]

    def __str__(self):
        return f"Registration: {self.citizen.full_name} by {self.officer.full_name}"


# ==================== Import Models ====================

class ImportLog(models.Model):
    """
    Tracks Excel file import operations with statistics.
    """
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('PROCESSING', 'Processing'),
        ('COMPLETED', 'Completed'),
        ('FAILED', 'Failed'),
    ]

    file_path = models.CharField(max_length=255)
    county = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    sheet_name = models.CharField(max_length=100, default='Gaps')
    total_rows = models.IntegerField(default=0)
    processed_count = models.IntegerField(default=0)
    skipped_count = models.IntegerField(default=0)
    duplicate_count = models.IntegerField(default=0)
    failed_count = models.IntegerField(default=0)
    errors = models.JSONField(default=list, blank=True, help_text='List of error records')
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='PENDING',
        db_index=True
    )
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['status']),
            models.Index(fields=['county']),
            models.Index(fields=['created_at']),
        ]

    def __str__(self):
        return f"Import: {self.file_path} - {self.status}"


# ==================== Audit Models ====================

class AuditLog(models.Model):
    """
    Immutable audit trail of all system actions.
    """
    ACTION_CHOICES = [
        ('LOGIN', 'Login'),
        ('LOGOUT', 'Logout'),
        ('REGISTER', 'Register Citizen'),
        ('PIN_CHANGE', 'PIN Changed'),
        ('PIN_ISSUED', 'PIN Issued'),
        ('OFFICER_CREATE', 'Officer Created'),
        ('OFFICER_UPDATE', 'Officer Updated'),
        ('OFFICER_DEACTIVATE', 'Officer Deactivated'),
        ('CAMPAIGN_CREATE', 'Campaign Created'),
        ('CAMPAIGN_UPDATE', 'Campaign Updated'),
        ('PIN_RESET', 'PIN Reset'),
        ('VERIFICATION_APPROVE', 'Verification Approved'),
        ('VERIFICATION_REJECT', 'Verification Rejected'),
    ]

    ENTITY_TYPE_CHOICES = [
        ('CITIZEN', 'Citizen'),
        ('OFFICER', 'Officer'),
        ('CAMPAIGN', 'Campaign'),
        ('REGISTRATION', 'Registration'),
    ]

    user = models.ForeignKey(Officer, on_delete=models.SET_NULL, null=True, related_name='audit_logs')
    action = models.CharField(max_length=50, choices=ACTION_CHOICES, db_index=True)
    entity_type = models.CharField(max_length=50, choices=ENTITY_TYPE_CHOICES)
    entity_id = models.BigIntegerField(null=True, blank=True)
    ip_address = models.CharField(max_length=45, null=True, blank=True)
    user_agent = models.TextField(null=True, blank=True)
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'action']),
            models.Index(fields=['action']),
            models.Index(fields=['created_at']),
            models.Index(fields=['entity_type', 'entity_id']),
        ]

    def __str__(self):
        return f"{self.action} by {self.user} at {self.created_at}"

    def save(self, *args, **kwargs):
        """Audit logs are immutable - prevent updates."""
        if self.pk:
            raise ValueError("Audit logs cannot be modified after creation")
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        """Audit logs are immutable - prevent deletion."""
        raise ValueError("Audit logs cannot be deleted")
